### ISSUE TITLE
Bold text

### ISSUE THREAD

**Issue by ngladitz** [drudru/ansi_up#44]
`ansi_to_html("foo \033[1mbar \033[mbaz")` somewhat unexpectedly produces
`foo <span style="color:rgb(255,255,255)">bar </span>baz`

SGR code 1 is meant to turn text "Bold".
While the library description only seems to explicitly address color I'd expect either 
`foo <span style="font-weight: bold;">bar </span>baz` or the code to be ignored.

**Comment by ngladitz** [comment]
Hi, thanks for looking into this.
I am not sure I understand your comments though.

As I said and as the Wikipedia article you linked states SGR code 1 is "Bold" not the color code for white so the current behavior is still unexpected.

**Comment by drudru** [comment]
In the first paragraph of:
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**"Quite a few terminals implemented "bold" (SGR code 1) as a brighter color rather than a different font, thus providing 8 additional foreground colors."**

I implemented to that spec. This is why I cannot even recall getting an issue about this. The vast majority of old code out there worked with this assumption.

**Still**

Your command line test is completely valid. I looked at the color compatibility chart for other terminals. The support is there, so maybe it is time to change things.

Tomorrow I will start work on a new minor version of ansi_up. It will treat bold as bold by default.
I will then add an optional api call to allow the old behaviour. I will keep this open the code lands.

Thank you

**Comment by ngladitz** [comment]
Awesome, thank you! :)

**Comment by drudru** [comment]
This has now been released - https://github.com/drudru/ansi_up/tree/v3.0.0

**Comment by ngladitz** [comment]
Works for me! Thanks again.
