### ISSUE TITLE
automatic links from http/https text

### ISSUE THREAD

**Issue by vanous** [drudru/ansi_up#70]
Hello,

thank you for all the awesome work and maintenance, much appreciated!

Would it be possible to have URLs to be detected automatically and be converted to [weblinks](https://github.com/drudru/ansi_up/issues/51)?

Thank you very much.

**Comment by drudru** [comment]
Hi, thanks.

Unfortunately, I have experience with that feature. I implemented it in the past and it was too difficult to get right *and* secure. The issue is the streaming nature of the data.

The library does support the OSC tag for a URL, but you would need something to perform that wrapping before passing it to ansi_up.

**Comment by vanous** [comment]
> Hi, thanks.
> 
> Unfortunately, I have experience with that feature. I implemented it in the past and it was too difficult to get right _and_ secure. The issue is the streaming nature of the data.
> 
> The library does support the OSC tag for a URL, but you would need something to perform that wrapping before passing it to ansi_up.

Thank you for the expertise on this, much appreciated.
